version: "3"
services:
  activemq:
    image: javacream/activemq:5.15.8
    container_name: activemq_5.15.8
    ports:
      - 61616:61616
      - 5672:5672
      - 61613:61613
      - 1883:1883
      - 61614:61614
      - 8161:8161
    volumes:
      - activemq_bin:/opt/activemq/bin
      - activemq_conf:/opt/activemq/conf
      - activemq_data:/opt/activemq/data
volumes:
  activemq_bin:
  activemq_conf:
  activemq_data: